---

- name: "conf: Add Sieve protocol to /usr/local/etc/dovecot/dovecot.conf"
  lineinfile:
    dest: "/usr/local/etc/dovecot/dovecot.conf"
    regexp: "^protocols"
    line: "protocols = {{ freebsd_mailserver_dovecot_protocols }}"
    backup: yes
  notify: reload dovecot

- name: "conf: Configure /usr/local/etc/dovecot/conf.d/10-director.conf"
  lineinfile:
    dest: "/usr/local/etc/dovecot/conf.d/10-director.conf"
    insertafter: "^protocol lmtp"
    regexp: "{{ item.regexp }}"
    line: "{{ item.regexp }} = {{ item.value }}"
    backup: yes
  loop: "{{ fm_ds_director }}"
  notify: reload dovecot
  
- name: "conf: Configure /usr/local/etc/dovecot/conf.d/15-lda.conf"
  lineinfile:
    dest: "/usr/local/etc/dovecot/conf.d/15-lda.conf"
    insertafter: "protocol lda {"
    regexp: "{{ item.regexp }}"
    line: "{{ item.regexp }} = {{ item.line }}"
    backup: yes
  loop: "{{ fm_ds_lda }}"
  notify: reload dovecot
                          
- name: "conf: Configure /usr/local/etc/dovecot/conf.d/20-lmtp.conf"
  lineinfile:
    dest: "/usr/local/etc/dovecot/conf.d/20-lmtp.conf"
    insertafter: "protocol lmtp {"
    regexp: "^mail_plugins"
    line: "mail_plugins = quota, sieve"
    backup: yes
  notify: reload dovecot

- name: "conf: Configure /usr/local/etc/dovecot/conf.d/90-plugin.conf"
  template:
    src: "90-plugin.conf"
    dest: "/usr/local/etc/dovecot/conf.d/90-plugin.conf"
    owner: "root"
    group: "www"
    mode: "0644"
    backup: yes
  notify: reload dovecot

# EOF
...
