---

- name: Add Sieve protocol to /usr/local/etc/dovecot/dovecot.conf
  lineinfile: >
    dest="/usr/local/etc/dovecot/dovecot.conf"
    regexp="^protocols"
    line="protocols = {{ freebsd_mailserver_dovecot_protocols }}"
    backup="yes"
  notify: reload dovecot
  tags: config_dovecot_sieve

- name: Configure /usr/local/etc/dovecot/conf.d/10-director.conf
  lineinfile: >
    dest="/usr/local/etc/dovecot/conf.d/10-director.conf"
    insertafter="^protocol lmtp"
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    backup="yes"
  with_items:
    - { regexp: "mail_plugins",  line: "mail_plugins = $mail_plugins sieve"}
    - { regexp: "log_path",  line: "log_path = /var/log/dovecot-lmtp-errors.log"}
    - { regexp: "info_log_path",  line: "info_log_path = /var/log/dovecot-lmtp.log"}
  notify: reload dovecot
  tags: config_dovecot_sieve
  
- name: Configure /usr/local/etc/dovecot/conf.d/15-lda.conf
  lineinfile: >
    dest="/usr/local/etc/dovecot/conf.d/15-lda.conf"
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    insertafter="protocol lda {"
    backup="yes"
  with_items:
    - { regexp: "mail_plugins",  line: "mail_plugins = $mail_plugins sieve"}
  notify: reload dovecot
  tags: config_dovecot_sieve
                          
- name: Configure /usr/local/etc/dovecot/conf.d/20-lmtp.conf
  lineinfile: >
    dest="/usr/local/etc/dovecot/conf.d/20-lmtp.conf"
    regexp="^mail_plugins"
    line="mail_plugins = quota, sieve"
    insertafter="protocol lmtp {"
    backup="yes"
  notify: reload dovecot
  tags: config_dovecot_sieve

- name: Configure /usr/local/etc/dovecot/conf.d/90-plugin.conf
  template: >
    src="90-plugin.conf"
    dest="/usr/local/etc/dovecot/conf.d/90-plugin.conf"
    backup="yes"
    owner="root"
    group="www"
    mode="0644"
  notify: reload dovecot
  tags: config_dovecot_sieve

# EOF
...
