---

- name: "freebsd-mailserver-sieve Debug"
  vars:
    msg: |
         ansible_architecture [ {{ ansible_architecture }} ]
         ansible_os_family [ {{ ansible_os_family }} ]
         ansible_distribution [ {{ ansible_distribution }} ]
         ansible_distribution_major_version [ {{ ansible_distribution_major_version }} ]
         ansible_distribution_version [ {{ ansible_distribution_version }} ]
         ansible_distribution_release [ {{ ansible_distribution_release }} ]

         freebsd_install_method [ {{ freebsd_install_method }} ]
         freebsd_use_packages [ {{ freebsd_use_packages }} ]
         freebsd_mailserver_dovecot_protocols [ {{ freebsd_mailserver_dovecot_protocols }} ]
         fm_ds_backup_conf [ {{ fm_ds_backup_conf }} ]
         fm_ds_packages
         {{ fm_ds_packages | to_nice_yaml }}
         fm_ds_director
         {{ fm_ds_director | to_yaml }}
         fm_ds_lda
         {{ fm_ds_lda | to_yaml }}
  debug:
    msg: "{{ msg.split('\n') }}"

# EOF
...
