---
# tasks file for vbotka.freebsd-mailserver-sieve

- include: packages.yml
  tags:
    - bsd_packages
    - bsd_ports
    - freebsd-mailserver-sieve

- include: config_dovecot_sieve.yml
  tags:
    - config_dovecot_sieve
    - freebsd-mailserver-sieve

# EOF
...
