---
# tasks for freebsd-mailserver-sieve

- import_tasks: debug.yml
  when: fm_ds_debug
  tags: [fm-ds-debug, always]

- import_tasks: packages.yml
  tags: fm-ds-packages

- import_tasks: conf.yml
  tags: fm-ds-conf

# EOF
...
