---
# tasks file for vbotka.ansible-freebsd-mailserver-sieve

- include: packages.yml
  tags: packages, freebsd-mailserver-sieve

- include: config_dovecot_sieve.yml
  tags: config_dovecot_sieve, freebsd-mailserver-sieve
