---
# tasks for freebsd_mailserver_sieve

- import_tasks: debug.yml
  when: fm_ds_debug|bool
  tags: [fm-ds-debug, always]

- import_tasks: packages.yml
  when: fm_ds_install|bool
  tags: fm-ds-packages

- import_tasks: sanity.yml
  when: fm_ds_sanity|bool
  tags: fm-ds-sanity

- import_tasks: conf.yml
  tags: fm-ds-conf

# EOF
...
