---
# handlers for freebsd_mailserver_sieve

- name: Reload dovecot
  listen: reload dovecot
  ansible.builtin.service:
    name: dovecot
    state: reloaded
  when: fm_dovecot_enable | d(false) | bool

- name: Restart dovecot
  listen: restart dovecot
  ansible.builtin.service:
    name: dovecot
    state: restarted
  when: fm_dovecot_enable | d(false) | bool

# EOF
