---
# handlers for freebsd_mailserver_sieve

- name: reload dovecot
  ansible.builtin.service:
    name: dovecot
    state: reloaded
  when: fm_dovecot_enable|default(false)|bool

- name: restart dovecot
  ansible.builtin.service:
    name: dovecot
    state: restarted
  when: fm_dovecot_enable|default(false)|bool

# EOF
...
